### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by TheSwifter** [zhxnlai/ZLSwipeableViewSwift#32] opened 2016-02-11 15:29 UTC
I was testing your great library !
But, I noticed some strange behaviour :
When I was moving the the first card, I can move also all cards below it.
![img_0832](https://cloud.githubusercontent.com/assets/11540455/12980342/5efb5d40-d0dc-11e5-81a2-a9bd50324bbd.PNG)

I think you may set userIntereactionEnabled = true only for the first card..

**Comment by AndrewSB** [comment] 2016-02-12 15:46
I feel as if being able to swipe multiple cards is a feature, not a bug. Could see a use case where you'd want that behavior and it seems easier to disable it in your case, than it would be to implement it in the other case.

Were you able to set `userIntereactionEnabled = true` only for the first card?
It may be worth it to add your expected behavior as a configurable option, a boolean `onlySwipeTopCard`

**Comment by TheSwifter** [comment] 2016-02-16 14:59
I think that making all cards manipulable by the user it is not a good idea. It can easily confuse the user specially with some UI treatments associated with swipe directions. I think that unlocking the interaction only the first card provides a better UX for the user.

But, setting a boolean flag  `onlySwipeTopCard` may be a good idea too to satisfy all tastes, who knows :)

**Comment by zhxnlai** [comment] 2016-02-16 17:39
The easiest way to enable only the first card is probably changing 
[this line](https://github.com/zhxnlai/ZLSwipeableViewSwift/blob/master/ZLSwipeableViewSwift/ZLSwipeableView.swift#L268) to `view.userInteractionEnabled = i == 0`
I found that doing so impacts the smoothness when swiping very fast. Please let me know if this is the case for you.

**Comment by TheSwifter** [comment] 2016-02-17 10:24
I tested it on **iPhone6/ iOS9.2.1** and **iPhone5/iOS8** and it works fine.

**Comment by AndrewSB** [comment] 2016-02-17 17:15
merged!

**Closed as completed by AndrewSB** 2016-02-17 17:15 UTC
