### ISSUE TITLE
fatal error: Can't form Range with end < start

### ISSUE THREAD

**Issue by sgandro** [zhxnlai/ZLSwipeableViewSwift#78] opened 2016-10-08 09:37 UTC
Hi Z,
when I try to call rewind() method int  didEnd closure.. I receive this error
fatal error: Can't form Range with end < start

I need to go next when I swipe to left, and go back when I swipe to right.

Can I help me!!?? 

Thx

**Comment by AndrewSB** [comment] 2016-10-29 20:42
Hey @sgandro! This is a duplicate of #59 and #49, and #64 should have fixed this crash.

Can you double check that you're using the latest version of this library?

**Closed as completed by AndrewSB** 2016-10-29 20:42 UTC
