### ISSUE TITLE
Update Cocoapod

### ISSUE THREAD

**Issue by JJLewis** [zhxnlai/ZLSwipeableViewSwift#119] opened 2017-11-28 06:32 UTC
The current version available through Cocoapods (0.0.7) does not build (109 errors) on new projects as it uses an older version of this project.
It would be great if the maintainer could update the Cocoapod. Thanks heaps.

**Comment by rafellk** [comment] 2017-12-03 02:12
Yes, that's exactly the issue

**Comment by AndrewSB** [comment] 2017-12-06 04:21
This has been an issue since #91, I don't think @zhxnlai is interested in maintaining the project and I don't feel like figuring out how to use Cocoapods. There's a workaround mentioned there that should work for y'all

```
pod 'ZLSwipeableViewSwift', :git => 'https://github.com/zhxnlai/ZLSwipeableViewSwift.git', :commit => '<pick a commit hash off master>'
```

**Comment by AndrewSB** [comment] 2018-03-12 17:29
Closing as dupe of #91, and more recently #111

**Closed as completed by AndrewSB** 2018-03-12 17:29 UTC
